<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>Kanani</Authors>
    <Version>3.0.1</Version>
    <Title>Utils</Title>
    <Product>Kanani</Product>
    <Description>My Tools</Description>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	  <PackageReference Include="AutoMapper" Version="13.0.1" />
	  <PackageReference Include="NPOI" Version="2.7.1" />

  </ItemGroup>


</Project>
