<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>$(FilterTools)</PackageId>
    <Title>DynamicFilter</Title>
    <Authors>$(Filter)</Authors>
    <Company>Kannani</Company>
    <Description>a tools for dynamic filter</Description>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Product>Kannani</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
